version: "3.4"

services:
  interview:
    container_name: interview
    build:
      context: ./interview
      dockerfile: Dockerfile
    volumes:
      - './interview:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@interview-db:5432/interview_db
      - DATABASE_TEST_URL=postgres://postgres:postgres@interview-db:5432/interview_testdb
      - SECRET_KEY=my_precious
    depends_on:
      - interview-db
    links:
      - interview-db

  interview-db:
    container_name: interview-db
    build:
      context: ./interview/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PROFILE=postgres
      - POSTGRES_PASSWORD=postgres
