version: "3.4"

services:
  interview:
    container_name: interview
    build:
      context: ./interview
      dockerfile: Dockerfile
    volumes:
      - './interview:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@interview-db:5432/interview_db
      - DATABASE_TEST_URL=postgres://postgres:postgres@interview-db:5432/interview_testdb
      - SECRET_KEY=my_precious
    depends_on:
      - interview-db
    links:
      - interview-db

  interview-db:
    container_name: interview-db
    build:
      context: ./interview/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PROFILE=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - interview

  swagger:
    container_name: swagger
    build:
      context: ./swagger
      dockerfile: Dockerfile
    volumes:
      - './swagger/swagger.yaml:/usr/share/nginx/html/swagger.yaml'
    ports:
      - '3008:8080'
    environment:
      - URL=swagger.yaml
    depends_on:
      - interview